baseURL = '/'
locale = 'en-us'
title = 'Artisanal'
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    min = '0.158.0'

[params.artisanal]
  accent = '#5c9574'
  accentText = '#245c40'
  dateFormat = 'Jan 2, 2006'
  headerMark = 'mark.svg'
  titleSeparator = '·'
